# Generated by Django 4.2.11 on 2024-07-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('article_number', models.CharField(max_length=50, verbose_name='Артикул')),
                ('price', models.FloatField(blank=True, max_length=15, null=True, verbose_name='Цена')),
                ('purchase_price', models.FloatField(blank=True, max_length=15, null=True, verbose_name='Закупочная цена')),
                ('remains', models.FloatField(blank=True, max_length=15, null=True, verbose_name='Остаток')),
                ('remains_cost', models.FloatField(blank=True, max_length=15, null=True, verbose_name='Стоимость остатка')),
                ('retail_remains_cost', models.FloatField(blank=True, max_length=15, null=True, verbose_name='Закупочная стоимость остатка')),
                ('percent', models.FloatField(blank=True, max_length=15, null=True, verbose_name='Процент')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category', verbose_name='Категория')),
            ],
        ),
    ]
