# Generated by Django 4.2.11 on 2024-07-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_maincategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'Общая категория', 'verbose_name_plural': 'Общие категории'},
        ),
    ]
