# Generated by Django 4.2.11 on 2024-07-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
