# Generated by Django 4.2.11 on 2024-08-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_icon_class_maincategory_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_category_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Изображение'),
        ),
    ]
