# Generated by Django 4.2.11 on 2024-09-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_remove_shoppingcart_products_cartitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_delivery', 'Ожидает вручения'), ('assembling', 'В сборке'), ('confirmed', 'Подтвержден'), ('received', 'Получен'), ('canceled', 'Отменен'), ('returned', 'Возвращен')], default='confirmed', max_length=20),
        ),
    ]
