# Generated by Django 4.2.11 on 2024-10-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_discount_order_final_price_order_promo_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_delivery', 'Ожидает вручения'), ('assembling', 'В сборке'), ('confirmed', 'Заказ создан'), ('received', 'Получен'), ('canceled', 'Отменен'), ('returned', 'Возвращен')], default='confirmed', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
